### ISSUE TITLE
Namespace Vault Parameters

### ISSUE THREAD

**Issue by Techcadia** [JetBrains/teamcity-hashicorp-vault-plugin#10]
I would like to run multiple copies of the vault-plugin. We have a few globally accessible items but we also have some more restricted passwords that should only be accessible via a single project.

Looking [at this line](https://github.com/JetBrains/teamcity-hashicorp-vault-plugin/blob/master/common/src/main/kotlin/org/jetbrains/teamcity/vault/VaultConstants.kt#L26) its has a constant of `vault:*` but it would really be nice if you could just configure in the UI a namespace for example `vault_my:*` This would allow me to access both the top level vault definition and the single project definition without conflict.

**Comment by VladRassokhin** [comment]
I've just merged PR #12 which adds support for multiple namespaces.

If connection namespace is set to 'ns' references would be `%vault:ns:/path%`
For default (empty) namespace it's still `%vault:/path%` to keep backward compatibility.
