### ISSUE TITLE
Remove restriction on namespaces

### ISSUE THREAD

**Issue by luisxkimo** [JetBrains/teamcity-hashicorp-vault-plugin#29]
Hi,

I cannot connect to my namespace because there is a regular expression restriction on the namespace name:

![image](https://user-images.githubusercontent.com/6990299/79763178-fffbaf80-8323-11ea-8afb-10209c14da7a.png)

It's possible remove or bypass this restriction?

**Comment by VladRassokhin** [comment]
Seems reasonable to allow hyphens as well. I'm trying to keep parameters as simple as possible
