### ISSUE TITLE
Allow stopping build process in case of unable to communicate with Vault

### ISSUE THREAD

**Issue by sugdyzhekov** [JetBrains/teamcity-hashicorp-vault-plugin#3]
In many cases, it is useless to continue to build w/o some data from Vault.

**Comment by IainColledge** [comment]
Agree 100% passing the path to a secret isn't valuable, the process should abort.

**Comment by varsy** [comment]
Would you kindly do this since we're using your lovely plugin every day for production deployments and it's essential to stop the whole process when Vault doesn't work, please?

**Comment by ghost** [comment]
+1

**Comment by VladRassokhin** [comment]
I've added checkbox in Connection settings
