### ISSUE TITLE
Teamcity2018.2.4 and Vault 1.4.0 plugin

### ISSUE THREAD

**Issue by ASethi93** [JetBrains/teamcity-hashicorp-vault-plugin#32]
<img width="1023" alt="Screen Shot 2020-05-16 at 6 40 05 PM" src="https://user-images.githubusercontent.com/28231762/82131599-d27c1780-97a4-11ea-9ea7-5907d57bad56.png">

ERROR: I/O error on POST request for "https://10.101.4.147:8200/v1/auth/approle/login": Connect to 10.101.4.147:8200 [/10.101.4.147] failed: connect timed out; nested exception is org.apache.http.conn.ConnectTimeoutException: Connect to 10.101.4.147:8200 [/10.101.4.147] failed: connect timed out

**Comment by ASethi93** [comment]
curl --request POST --data @payload.json https://localhost:8200/v1/auth/approle/login | jq
Returns value : 
{
  "request_id": "xxxx",
  "lease_id": "",
  "renewable": false,
  "lease_duration": 0,
  "data": null,
  "wrap_info": null,
  "warnings": null,
  "auth": {
    "client_token": "cccccc",
    "accessor": "jHEWbDuh8ybMd17fZLaA1tKH",
    "policies": [
      "default",
      "teamcity"
    ],
    "token_policies": [
      "default",
      "teamcity"
    ],
    "metadata": {
      "role_name": "teamcity"
    },
    "lease_duration": 3600,
    "renewable": true,
    "entity_id": "vvvbbbbbn",
    "token_type": "service",
    "orphan": true
  }
}

**Comment by ASethi93** [comment]
ACL POlicy looks like 
path "auth/approle/login"
{
  capabilities = ["create", "read", "update", "delete", "list", "sudo"]
}
path "secret/teamcity/Username" {
  capabilities = [ "read" ]
}
path "secret/teamcity/password" {
  capabilities = [ "read" ]
}
path "secret/teamcity/url" {
  capabilities = [ "read" ]
}

**Comment by ASethi93** [comment]
vault auth list
Path        Type       Accessor                 Description
----        ----       --------                 -----------
approle/    approle    auth_approle_dde52b1d    n/a
aws/        aws        auth_aws_9bff89c9        n/a
github/     github     auth_github_79f67a47     n/a
token/      token      auth_token_3ef2645a      token based credentials

**Comment by Albibek** [comment]
Not sure, why are you asking me. I'm not a JetBrain representative and not an author of this plugin either. 
Anyways it is more likely that you have a network problem of reaching Vault from TeamCity. Check your network, DNS and firewall settings on agents and the TeamCity servers.

**Comment by VladRassokhin** [comment]
From error message
> failed: connect timed out

Clearly shows that TeamCity server is unable to connect your Vault instance. Check network connectivity

**Comment by ASethi93** [comment]
@VladRassokhin 
Regarding this step in the documentation: Configure secret backends in Vault to obtain secrets, for example, AWS credentials, or generic secrets.
do I need the TeamCity login credentials or the vault credentials to access successfully

**Comment by VladRassokhin** [comment]
You need to specify only vault credentials (approle id and secret)

**Comment by ASethi93** [comment]
The connectivity is completely fine when I dig +short from teamcity server to vault and vice versa , i get answer , but when i test the connectivity in teamcity UI it fails : I/O error on POST request for "https://vault.ns.net:8200/v1/auth/approle/login": vault.ns.net: Name or service not known; nested exception is java.net.UnknownHostException: vault.ns.net: Name or service not known

**Comment by VladRassokhin** [comment]
Looks like TC server is unable to resolve DNS name, that's quite strange.

Please try following test on host with TeamCity server:
1. Place somewhere file `TestNetConnection.java` with content:
```java
import java.net.URL;
import java.io.*;
import javax.net.ssl.HttpsURLConnection;
public class TestNetConnection {
    public static void main(String[] args) throws Exception {
        String httpsURL = args[0];
	System.out.println("Trying to connect to '" + httpsURL + "' ...");
        URL myUrl = new URL(httpsURL);
        HttpsURLConnection conn = (HttpsURLConnection)myUrl.openConnection();
        InputStream is = conn.getInputStream();
	System.out.println("Connected, response body is:");
        BufferedReader br = new BufferedReader(new InputStreamReader(is));
        String inputLine;
        while ((inputLine = br.readLine()) != null) {
            System.out.println(inputLine);
        }
        br.close();
    }
}
```
2. Run `javac TestNetConnection.java`
3. Run `java TestNetConnection https://vault.ns.net:8200`
