### ISSUE TITLE
Pass Vault token to build steps as a parameter

### ISSUE THREAD

**Issue by slavikb** [JetBrains/teamcity-hashicorp-vault-plugin#46]
It would be convenient to make Vault token available to build steps as a special parameter (like %vault:$token%)

Build scripts can use this value to perform custom requests to Vault to use secrets engines other than key-value store (e.g. sign custom SSH certificates, access AD passwords and so on).
Considering security, it would be preferable for agents to use prepared temporary token from the server (obtained through AppRole or other method) instead of authenticating to Vault on their own.

**Comment by VladRassokhin** [comment]
There's `%env.VAULT_TOKEN%` or `%env.NAMESPACE_VAULT_TOKEN%` (replace NAMESPACE with uppercase name of namespace)

It's available if you add special build parameter (set to `true`): `teamcity.vault.set.env` or `teamcity.vault.${NAMESPACE}.set.env` if namespace is not null.

**Comment by slavikb** [comment]
Super, just what is needed!:)

**Comment by serpro69** [comment]
Hi,
Trying to achieve the same. Where exactly should this parameter be set?
Thanks
