### ISSUE TITLE
Is this plugin dead?

### ISSUE THREAD

**Issue by Briansbum** [JetBrains/teamcity-hashicorp-vault-plugin#7]
There doesn't seem to be much happening here and key features like support for the AWS backend don't seem to have gotten further than the initial blog post mentioning it's not working.

**Comment by VladRassokhin** [comment]
Nope, "It's alive".

I'd say plugin is feature complete for first version and we're using it internally without significant problems. Feature request and bug reports are welcome here in GitHub or in [YouTrack](https://youtrack.jetbrains.com/issues/TW).

What do you mean by: ?
>AWS backend don't seem to have gotten further than the initial blog post mentioning it's not working

Don't see any evidence in blog post that something is not working. Please point me to such facts.

**Comment by Briansbum** [comment]
Ok that's fair enough, thanks for the response.
