### ISSUE TITLE
Fix plugin documentation

### ISSUE THREAD

**Issue by byumov** [JetBrains/teamcity-hashicorp-vault-plugin#9]
I had a problem with Vault plugin after read documentation from post: https://blog.jetbrains.com/teamcity/2017/09/vault/

Correct format:
`%vault:secret/some/path!/somekey%`
From documentation:
`%vault:secret/some/path!somekey%`

Is the post  an only one official documentation?

There is a issue, which helped me to solve the problem: https://github.com/JetBrains/teamcity-hashicorp-vault-plugin/issues/1

But, documentation is still incorrect. Fix it, please.

**Comment by yoshikakbudto** [comment]
with vault 1.1.3

### For K/V version 2
For the cli request:  ```vault kv get -field=foo kv/cicd/blue```

the correct syntaxes (note /data/):
1. %vault:kv/data/cicd/blue!/foo%
1. %vault:/kv/data/cicd/blue!/foo%

### For K/V version 1
For the cli request:  ``vault kv get -field=user kv1/creds```
the correct syntaxes is:
1. %vault:kv1/creds!/user%
1. %vault:/kv1/creds!/user%

### For the future path problems, to find the correct path
1. enable Vault server audit logs. Forexample ```vault audit enable file file_path=/vault/logs/audit.log```
1. use vault CLI
1. search for the path in audit.log

**Comment by VladRassokhin** [comment]
Finally fixed plugin description and blog post.
